### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element

### ISSUE THREAD

**Issue by SayaliVB** [Ankit404butfound/PyWhatKit#11]
Hi, I am getting an error in pywhatkit.sendwhatmsg_with_selenium. Please help:
Traceback (most recent call last):
  File "C:\Users\INTEL\Videos\Python\whatsapp2.py", line 6, in <module>
    pywhatkit.sendwhatmsg_with_selenium("+91**********","This is a message", 20,7)
  File "C:\Python 32\lib\site-packages\pywhatkit\__init__.py", line 194, in sendwhatmsg_with_selenium
    msg_box = driver.find_element_by_xpath('//div[@contenteditable="true"][@data-tab="1"]')
  File "C:\Python 32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python 32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Python 32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python 32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@contenteditable="true"][@data-tab="1"]"}
  (Session info: headless chrome=84.0.4147.135) 

Also I am getting one more error:
Traceback (most recent call last):
  File "C:\Users\INTEL\Videos\Python\whatsapp2.py", line 6, in <module>
    pywhatkit.sendwhatmsg_with_selenium("+91**********","This is a message", 23,42)
  File "C:\Python 32\lib\site-packages\pywhatkit\__init__.py", line 190, in sendwhatmsg_with_selenium
    driver = webdriver.Chrome(path,options=options)
  File "C:\Python 32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Python 32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python 32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python 32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python 32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unable to discover open pages

**Comment by Ankit404butfound** [comment]
From newer version of PyWhatKit, the sendwhatmsg_with_selenium function has been dropped and it is no longer maintained because of its unpredictable behavior.

You have to manually update the function if you still want to use it. Open the __init__.py file of pywhatkit (type "pywhatkit" in Module Browser), replace everything on line number 194 with `msg_box = driver.find_element_by_class_name('input-container')` and save the edited file.

Now call that function again, it should work now.

**Comment by SayaliVB** [comment]
Hi, thanks for the update. I will try that. I am also getting this error now. Please help: 

Traceback (most recent call last):
File "C:\Users\INTEL\Videos\Python\whatsapp2.py", line 6, in
pywhatkit.sendwhatmsg_with_selenium("+91**********","This is a message", 23,42)
File "C:\Python 32\lib\site-packages\pywhatkit_init_.py", line 190, in sendwhatmsg_with_selenium
driver = webdriver.Chrome(path,options=options)
File "C:\Python 32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in init
desired_capabilities=desired_capabilities)
File "C:\Python 32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in init
self.start_session(capabilities, browser_profile)
File "C:\Python 32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
response = self.execute(Command.NEW_SESSION, parameters)
File "C:\Python 32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "C:\Python 32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unable to discover open pages

**Comment by Ankit404butfound** [comment]
Have a look at this
https://stackoverflow.com/questions/21001652/chrome-driver-error-using-selenium-unable-to-discover-open-pages
This might solve the problem.
