### ISSUE TITLE
sendwhats_image not supporting sending video files

### ISSUE THREAD

**Issue by ghadithrissur** [Ankit404butfound/PyWhatKit#114]
Hi There,

The documentation says the video is supported, I tried sending Video (.mp4) and I am getting an error. Code snippet and console logs are as follows.

pywhatkit.sendwhats_image('+91875446917','C:\\PJmasks.mp4','TSHIRTBUY Video',10,True,5)

Traceback (most recent call last):
  File "C:/Users/director/PycharmProjects/WhatsappMarking/venv/main.py", line 5, in <module>
    pywhatkit.sendwhats_image('+918754469109','C:\\PJmasks.mp4','TSHIRTBUY Video',10,True,5)
  File "C:\Users\director\PycharmProjects\WhatsappMarking\venv\lib\site-packages\pywhatkit\main.py", line 208, in sendwhats_image
    image = Image.open(img_path)
  File "C:\Users\director\PycharmProjects\WhatsappMarking\venv\lib\site-packages\PIL\Image.py", line 3024, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'C:\\PJmasks.mp4'

Thanks
TG

**Comment by aaryanrr** [comment]
Hey @ghadithrissur , that's a mistake in the documentation. The function currently doesn't support sending videos. We are finding a way to implement it. Thanks for pointing this out!
