### ISSUE TITLE
pywhatkit no internet error

### ISSUE THREAD

**Issue by Vortexano** [Ankit404butfound/PyWhatKit#135]
C:\Users\vx0105\PycharmProjects\pythonProject1\venv\Scripts\python.exe C:/Users/vx0105/PycharmProjects/pythonProject1/main.py
Traceback (most recent call last):
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
chunked=chunked,
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
self.validate_conn(conn)
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\urllib3\connectionpool.py", line 1010, in validate_conn
conn.connect()
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\urllib3\connection.py", line 426, in connect
tls_in_tls=tls_in_tls,
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\urllib3\util\ssl.py", line 450, in ssl_wrap_socket
sock, context, tls_in_tls, server_hostname=server_hostname
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\urllib3\util\ssl.py", line 493, in _ssl_wrap_socket_impl
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "C:\Users\vx0105\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 407, in wrap_socket
_context=self, _session=session)
File "C:\Users\vx0105\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 817, in init
self.do_handshake()
File "C:\Users\vx0105\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1077, in do_handshake
self._sslobj.do_handshake()
File "C:\Users\vx0105\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 689, in do_handshake
self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\requests\adapters.py", line 449, in send
timeout=timeout
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\urllib3\util\retry.py", line 574, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\pywhatkit\main.py", line 310, in
requests.get("https://www.google.com")
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\requests\api.py", line 75, in get
return request('get', url, params=params, **kwargs)
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\requests\api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\requests\sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\requests\sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\requests\adapters.py", line 514, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:/Users/vx0105/PycharmProjects/pythonProject1/main.py", line 3, in
import pywhatkit
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\pywhatkit_init_.py", line 8, in
from pywhatkit.main import print_sleep_time, check_window, sendwhatmsg, sendwhatmsg_to_group, info, playonyt, search, close_tab, sendwhatmsg_instantly, sendwhats_image
File "C:\Users\vx0105\PycharmProjects\pythonProject1\venv\lib\site-packages\pywhatkit\main.py", line 315, in
"NO INTERNET - Pywhatkit needs active internet connection")
pywhatkit.exceptions.InternetException: NO INTERNET - Pywhatkit needs active internet connection

Process finished with exit code 1

I am encountering this error when I run a programme which I tell to play a song for me, when I run the programme before i even give it any command it says internet error but I have internet access. How can I fix it?

**Comment by Ankit404butfound** [comment]
It seems the connection is getting timed out, I am not sure if this is possible but have you disabled network in your virtual environment?

**Comment by aaryanrr** [comment]
@Vortexano, is the issue resolved?
