### ISSUE TITLE
scheduling send messages using crontab

### ISSUE THREAD

**Issue by s33k3rs** [Ankit404butfound/PyWhatKit#150]
## Description

i want to use PyWhatkit and crontab to send messages once a day

## To Reproduce

i use crontab, bash script to call environment in anaconda and run script PyWhatkit to send message
crontab -e
`*/1 * * * * bash send.sh > /home/mypc/send.log 2>&1`

send.sh
```
source /home/mypc/anaconda3/etc/profile.d/conda.sh && \
conda activate waapi && \
python WA_Instant.py &

```
WA_Instant.py
```
#!/usr/bin/env python
# coding: utf-8
import pywhatkit
from datetime import datetime
# datetime object containing current date and time
now = datetime.now()
#print("now =", now)
# dd/mm/YY H:M:S
dt_string = now.strftime("%d/%m/%Y %H:%M:%S")
#print("date and time =", dt_string)	
pywhatkit.sendwhatmsg_instantly("+62***********", '*Send message at :* \n' + dt_string, 20, True, 5)


```

but I get an error message in the file send.log
```
Traceback (most recent call last):
  File "WA_Instant.py", line 7, in <module>
    import pywhatkit
  File "/home/mypc/PyWhatKit/pywhatkit/__init__.py", line 16, in <module>
    from pywhatkit.whats import (
  File "/home/mypc/PyWhatKit/pywhatkit/whats.py", line 7, in <module>
    import pyautogui as pg
  File "/home/mypc/anaconda3/envs/waapi/lib/python3.8/site-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/home/mypc/anaconda3/envs/waapi/lib/python3.8/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/home/mypc/anaconda3/envs/waapi/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'
```

## Version Information

- OS: [e.g. Ubuntu 18.04]
- Browser: [ Firefox, Google Chrome ]
- Python: [ 3.8.12]
- PyWhatKit: [e.g. 5.2]

How to fix this problem?

**Comment by aaryanrr** [comment]
Hey @s33k3rs, thanks for reaching out. This bug usually occurs when you don't have a display attached to your PC or it is not configured properly. If you have a display attached then add these lines at the start of your script:
```py
import os
os.environ['DISPLAY'] = ':0'
```

**Comment by s33k3rs** [comment]
Thx, it's running well

alternative i added on crontab
`DISPLAY=:0`
