### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by ishwart466** [Ankit404butfound/PyWhatKit#186]
Traceback (most recent call last):
  File "D:\pythonProject\main.py", line 1, in <module>
    import pywhatkit as pwt
  File "D:\pythonProject\venv\lib\site-packages\pywhatkit\__init__.py", line 16, in <module>
    from pywhatkit.whats import (
  File "D:\pythonProject\venv\lib\site-packages\pywhatkit\whats.py", line 9, in <module>
    from pywhatkit.core import core, exceptions, log
  File "D:\pythonProject\venv\lib\site-packages\pywhatkit\core\core.py", line 9, in <module>
    from pyautogui import click, hotkey, press, size, typewrite
ImportError: cannot import name 'click' from 'pyautogui' (D:\pythonProject\venv\lib\site-packages\pyautogui\__init__.py)

**Comment by Naman23-coder** [comment]
@ishwart466 can you please tell operating system and python version

**Comment by aaryanrr** [comment]
Hey @ishwart466, thanks for reaching out. Can you try reinstalling `pyautogui`. Follow these commands:
1. `pip3 uninstall pyautogui`
2. `pip3 install pyautogui`

**Comment by aaryanrr** [comment]
Can you try creating a new virtual environment?
