### ISSUE TITLE
Error on Import line.

### ISSUE THREAD

**Issue by xtendtech** [Ankit404butfound/PyWhatKit#21]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xtendtech** [comment]
> A clear and concise description of what the bug is.

Error showing on first line import in windows 10 
(whatsapp) PS C:\Users\admin> pip install pywhatkit
Requirement already satisfied: pywhatkit in c:\users\admin\whatsapp\lib\site-packages (3.2)
Requirement already satisfied: beautifulsoup4 in c:\users\admin\whatsapp\lib\site-packages (from pywhatkit) (4.9.3)
Requirement already satisfied: numpy in c:\users\admin\whatsapp\lib\site-packages (from pywhatkit) (1.19.4)
Requirement already satisfied: pyautogui in c:\users\admin\whatsapp\lib\site-packages (from pywhatkit) (0.9.52)
Requirement already satisfied: Pillow in c:\users\admin\whatsapp\lib\site-packages (from pywhatkit) (8.0.1)
Requirement already satisfied: requests in c:\users\admin\whatsapp\lib\site-packages (from pywhatkit) (2.6.0)
Requirement already satisfied: wikipedia in c:\users\admin\whatsapp\lib\site-packages (from pywhatkit) (1.4.0)
Requirement already satisfied: soupsieve>1.2; python_version >= "3.0" in c:\users\admin\whatsapp\lib\site-packages (from beautifulsoup4->pywhatkit) (2.0.1)
Requirement already satisfied: pygetwindow>=0.0.5 in c:\users\admin\whatsapp\lib\site-packages (from pyautogui->pywhatkit) (0.0Requirement already satisfied: PyTweening>=1.0.1 in c:\users\admin\whatsapp\lib\site-packages (from pyautogui->pywhatkit) (1.0.3)
Requirement already satisfied: pyscreeze>=0.1.21 in c:\users\admin\whatsapp\lib\site-packages (from pyautogui->pywhatkit) (0.1.26)
Requirement already satisfied: pymsgbox in c:\users\admin\whatsapp\lib\site-packages (from pyautogui->pywhatkit) (1.0.9)       
Requirement already satisfied: pyperclip in c:\users\admin\whatsapp\lib\site-packages (from mouseinfo->pyautogui->pywhatkit) (1.8.1)
Requirement already satisfied: pyrect in c:\users\admin\whatsapp\lib\site-packages (from pygetwindow>=0.0.5->pyautogui->pywhatkit) (0.1.4)
(whatsapp) PS C:\Users\admin> 
(whatsapp) PS C:\Users\admin> & c:/Users/admin/whatsapp/Scripts/python.exe c:/Users/admin/pywhatkit2.py^C
(whatsapp) PS C:\Users\admin> & c:/Users/admin/whatsapp/Scripts/python.exe c:/Users/admin/pywhatkit2.py
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "c:/Users/admin/pywhatkit2.py", line 1, in <module>
    import pywhatkit
  File "C:\Users\admin\whatsapp\lib\site-packages\pywhatkit\__init__.py", line 5, in <module>
    from pywhatkit.chr_to_handwriting import download, text_to_handwriting
  File "C:\Users\admin\whatsapp\lib\site-packages\pywhatkit\chr_to_handwriting.py", line 5, in <module>
    import numpy as np
  File "C:\Users\admin\whatsapp\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Users\admin\whatsapp\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\admin\\whatsapp\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

**Comment by xtendtech** [comment]
There is nothing except import pywhatkit as one line.
Numpi is updated
Requirement already satisfied: numpy in c:\users\admin\whatsapp\lib\site-packages (1.19.4)

**Comment by xtendtech** [comment]
Use pip install numpy==1.19.3
Issue with numpy which is a requirement for this library
