### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter' in Ubuntu 20.04

### ISSUE THREAD

**Issue by rohan-paul** [Ankit404butfound/PyWhatKit#210]
## To Reproduce

Just after importing like `import pywhatkit` getting below error

```
Traceback (most recent call last):
  File "/home/paul/.local/lib/python3.9/site-packages/mouseinfo/__init__.py", line 276, in <module>
    import tkinter
ModuleNotFoundError: No module named 'tkinter'

During the handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paul/.local/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_34419/1952111025.py", line 2, in <module>
    import pywhatkit
  File "/home/paul/.local/lib/python3.9/site-packages/pywhatkit/__init__.py", line 16, in <module>
    from pywhatkit.whats import (
  File "/home/paul/.local/lib/python3.9/site-packages/pywhatkit/whats.py", line 7, in <module>
    import pyautogui as pg
  File "/home/paul/.local/lib/python3.9/site-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/home/paul/.local/lib/python3.9/site-packages/mouseinfo/__init__.py", line 280, in <module>
    sys.exit('NOTE: You must install tkinter on Linux to use MouseInfo. Run the following: sudo apt-get install python3-tk python3-dev')
SystemExit: NOTE: You must install tkinter on Linux to use MouseInfo. Run the following: sudo apt-get install python3-tk python3-dev
```

- OS: Ubuntu 20.04

I have already done 

```
sudo apt-get install python3-tk python3-dev
sudo apt-get install python-tk
```

**Comment by lefado** [comment]
facing same issue

**Comment by Naman23-coder** [comment]
@rohan-paul and @lefado please try reinstalling official python release

**Comment by AlwaysBeCalm** [comment]
I faced it today and solved it using
```bash
sudo apt install python3.9-tk
```
and kept python3-dev as is.

**Comment by Parzival-ReadyPlayer** [comment]
sudo apt install python3.10-tk work for me, thanks AlwaysBeCalm!
