### ISSUE TITLE
Hosting on Heroku

### ISSUE THREAD

**Issue by noblexeyi** [Ankit404butfound/PyWhatKit#241]
I used the Pywhatkit python library to automate sending whatsapp messages, it's working very well in localhost, I realized I have to keep my PC on 24/7 for this to work. So I thought about hosting on Heroku (I don't know if that is possible), so I put it on heroku, but every time I try to run my script in heroku, I get the following error.

**Heroku Error**
```
Traceback (most recent call last):
  File "/app/test.py", line 2, in <module>
    import pywhatkit
  File "/app/.heroku/python/lib/python3.10/site-packages/pywhatkit/__init__.py", line 16, in <module>
    from pywhatkit.whats import (
  File "/app/.heroku/python/lib/python3.10/site-packages/pywhatkit/whats.py", line 7, in <module>
    import pyautogui as pg
  File "/app/.heroku/python/lib/python3.10/site-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/app/.heroku/python/lib/python3.10/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/app/.heroku/python/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'
```

**Code (Files)**

requirement.txt

`pywhatkit==5.4`

test.py

```
import pywhatkit

try:

    pywhatkit.sendwhatmsg_instantly("+1*********",
                                    "Hello from NewYork")
    print("Successfully Sent!")

except:

    print("An Unexpected Error!")
```

**Comment by Ankit404butfound** [comment]
The library is not desigend to work without any attached display, it will not work if there is not external monitor connected to the system through hdmi or vga or anything else, as in the cas eof heroku.
