### ISSUE TITLE
Unable to import pywhatkit in Termux

### ISSUE THREAD

**Issue by TheShubhendra** [Ankit404butfound/PyWhatKit#25]
- Python: 3.9.0
- Vncserver : tigervnc 1.10.1

```bash
Python 3.9.0 (default, Oct  8 2020, 15:54:02)
[Clang 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywhatkit
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/Xlib/support/unix_connect.py", line 76, in get_socket
    s.connect('/tmp/.X11-unix/X%d' % dno)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywhatkit/__init__.py", line 4, in <module>
    from pywhatkit.mainfunctions import sendwhatmsg_to_group, watch_tutorial_in_English, watch_tutorial_in_Hindi, developer_contact, showHistory, shutdown, cancelShutdown, prnt_sleeptm, check_window, sendwhatmsg, info, playonyt, image_to_ascii_art, search
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywhatkit/mainfunctions.py", line 3, in <module>
    import pyautogui as pg
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyautogui/__init__.py", line 241, in <module>
    import mouseinfo
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/Xlib/protocol/display.py", line 58, in __init__
    self.socket = connect.get_socket(name, host, displayno)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/Xlib/support/connect.py", line 76, in get_socket
    return mod.get_socket(dname, host, dno)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/Xlib/support/unix_connect.py", line 78, in get_socket
    raise error.DisplayConnectionError(dname, str(val))
Xlib.error.DisplayConnectionError: Can't connect to display ":4": [Errno 2] No such file or directory```

**Comment by aaryanrr** [comment]
Its something related to your vnc server not pywhatkit.

**Comment by TheShubhendra** [comment]
Issue moved  to https://github.com/python-xlib/python-xlib/issues/188#issuecomment-756673972.

**Comment by Manojwithcode** [comment]
File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywhatkit/__init__.py" 
bhai ye problem  solve  nahi ho rahi he

**Comment by Naman23-coder** [comment]
@Manojwithcode try 'pip install pywhatkit --upgrade'
