### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by DmytroHladkyi** [Ankit404butfound/PyWhatKit#278]
i have this code: 
import pywhatkit
def searching_info():
    query = input("What are zou looking for?: ")
    pywhatkit.search(query)     
def main():
    searching_info()
if __name__ == '__main__':
    main()
and then I get this error: 
Traceback (most recent call last):
  File "c:\Users\Hladkyi Dmytro\Desktop\IT Oprogromowanie\Python_Projects\test.py", line 1, in <module>
    import pywhatkit
  File "C:\Users\Hladkyi Dmytro\AppData\Local\Programs\Python\Python311\Lib\site-packages\pywhatkit\__init__.py", line 11, in <module>
    from pywhatkit.ascii_art import image_to_ascii_art
  File "C:\Users\Hladkyi Dmytro\AppData\Local\Programs\Python\Python311\Lib\site-packages\pywhatkit\ascii_art.py", line 3, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

**Comment by sudhir2016** [comment]
Facing same issue

**Comment by ainacodes** [comment]
run this:
```
pip3 install Pillow
```
