### ISSUE TITLE
pywhatkit.sendwhatmsg_to_group discards all non-Latin letters

### ISSUE THREAD

**Issue by Jariihanainen** [Ankit404butfound/PyWhatKit#348]
## Description

Everything is working fine when sending with pywhatkit.sendwhatmsg to one person, but when sending to group all
non-latin characters disappears (like ä,ö etc...)

## Version Information

- OS: ALMA LINUX 9
- Browser: Firefox
- Python: 3.9.18
- PyWhatKit: 5.3

**Comment by kidstell** [comment]
https://github.com/Ankit404butfound/PyWhatKit/issues/346

kindly confirm if the solution here fixes your requirement.

**Comment by Jariihanainen** [comment]
Hi

Thanks for your help
I'm still unable to send messages to group

Now I get error:

Traceback (most recent call last):
  File "/root/send-messages_final.py", line 25, in <module>
    pywhatkit.sendwhatmsg_to_group('XXXXXXXXXXXX',(my_string1+'\n'+my_string2+'\n'+my_string3), 10, 52)
  File "/usr/local/lib/python3.9/site-packages/pywhatkit/whats.py", line 111, in sendwhatmsg_to_group
    core.send_message(message=message, receiver=group_id, wait_time=wait_time)
  File "/usr/local/lib/python3.9/site-packages/pywhatkit/core/core.py", line 71, in send_message
    keyboard.write(char)
  File "/usr/local/lib/python3.9/site-packages/keyboard/__init__.py", line 854, in write
    scan_code, modifiers = next(iter(entries))
StopIteration


And for some reason same code working when sending to one phone number

Kind Regards

Jari
Lähettäjä: Agbayewa Adetunji ***@***.***>
Lähetetty: tiistai 26. marraskuuta 2024 2.47
Vastaanottaja: Ankit404butfound/PyWhatKit ***@***.***>
Kopio: Jari Ihanainen ***@***.***>; Author ***@***.***>
Aihe: Re: [Ankit404butfound/PyWhatKit] pywhatkit.sendwhatmsg_to_group discards all non-Latin letters (Issue #348)


#346<https://github.com/Ankit404butfound/PyWhatKit/issues/346>

kindly confirm if the solution here fixes your requirement.

-

**Comment by Jariihanainen** [comment]
I still suffer with this
When I'm using 
pywhatkit.sendwhatmsg('+358 XXX XXX XXX',(my_string1+'\n'+my_string2+'\n'+my_string3), 7, 25)
Everything is just fine
![to phone number](https://github.com/user-attachments/assets/75b5c0f2-b311-4f75-9cea-9ce8adae68b9)

**BUT**

Using
pywhatkit.sendwhatmsg_to_group('XXXXXXXXXXXXXX',(my_string1+'\n'+my_string2+'\n'+my_string3), 7, 40)
I lost all non-latin charactrs like ä,ö etc...
![to group](https://github.com/user-attachments/assets/c010517a-68b9-4182-8033-1086806167a3)

Please help, I really do not uderstand where is the different between sendwhatmsg and sendwhatmsg_to_group

**Comment by danielvartan** [comment]
[Lucas Bragança](https://stackoverflow.com/users/5843988/lucas-bragan%c3%a7a) suggested an effective [workaround](https://stackoverflow.com/a/43918010/8258804) for this issue: instead of using `pyautogui` to type special characters directly, it's better to copy the text to the clipboard with `pyperclip` and then paste it using `pyautogui`. This ensures that all characters are preserved.

As of now, the problem appears to be fixed in the developer version (I haven’t tested it), but for those sticking with the stable release, here’s a manual fix:

---

### Steps:

1. Open the following file: `./.venv/lib/python3.12/site-packages/pywhatkit/core/core.py`

*(If you’re not using a virtual environment, locate this file in your global Python site-packages directory.)*

2. Add the code below on line 7.

```python
import pyperclip
```

3. Replace the entire `send_message` function with the following code:

```python
def send_message(message: str, receiver: str, wait_time: int) -> None:
    """Parses and Sends the Message"""

    _web(receiver=receiver, message=message)
    time.sleep(7)
    click(WIDTH / 2, HEIGHT / 2)
    time.sleep(wait_time - 7)
    pyperclip.copy(message)
    if not check_number(number=receiver):
        if system() == "Darwin":
            hotkey("command", "v")
        else:
            hotkey("ctrl", "v")
    press("enter")
```

4. Restart your Python session and try sending group messages again.

**Comment by danielvartan** [comment]
The same fix also applies to the `sendwhats_image` caption issue.

---

### Steps:

1. Open the following file: `./.venv/lib/python3.12/site-packages/pywhatkit/core/core.py`

*(If you’re not using a virtual environment, locate this file in your global Python site-packages directory.)*

2. Add the code below on line 7.

```python
import pyperclip
```

3. Replace the entire `send_image` function with the following code:

```python
def send_image(path: str, caption: str, receiver: str, wait_time: int) -> None:
    """Sends the Image to a Contact or a Group based on the Receiver"""

    _web(message=caption, receiver=receiver)

    time.sleep(7)
    click(WIDTH / 2, HEIGHT / 2)
    time.sleep(wait_time - 7)
    pyperclip.copy(caption)
    if not check_number(number=receiver):
        if system() == "Darwin":
            hotkey("command", "v")
        else:
            hotkey("ctrl", "v")
    else:
        typewrite(" ")
    copy_image(path=path)
    if system().lower() == "darwin":
        hotkey("command", "v")
    else:
        hotkey("ctrl", "v")
    time.sleep(1)
    press("enter")
```

4. Restart your Python session and try sending group messages again.

**Comment by danielvartan** [comment]
While you're at it, remove the indicated line from `./.venv/lib/python3.12/site-packages/pywhatkit/whats.py`. It duplicates the delay time—probably something that went unnoticed.

```python
def sendwhatmsg_to_group_instantly(
    group_id: str,
    message: str,
    wait_time: int = 15,
    tab_close: bool = False,
    close_time: int = 3,
) -> None:
    """Send WhatsApp Message to a Group Instantly"""
    
    current_time = time.localtime()

    time.sleep(wait_time)  # <---------------- !DELETE THIS LINE!
    core.send_message(message=message, receiver=group_id, wait_time=wait_time)
    log.log_message(_time=current_time, receiver=group_id, message=message)
    if tab_close:
        core.close_tab(wait_time=close_time)
```
